/*
* $Id: JOAResources.java,v 1.33 2005/10/18 23:42:18 oz Exp $
*
*/

package javaoceanatlas.resources;

import java.util.*;
import javaoceanatlas.ui.widgets.JOAJRadioButton;

/**
* Resource Bundle of menu item tokens and associated
* locale-specific labels.
*
* @author oz
* @version 1.0
*/

public class JOAResources extends ListResourceBundle {
  public Object[][] getContents() {
	  return contents;
  }

  static final Object[][] contents = {
	  // American English Menu Strings
	  {"kOK", "OK"},
	  {"kCancel", "Cancel"},
	  {"kFile", "File"},
	  {"kEditMenu", "Edit"},
	  {"kPreferences", "Preferences..."},
	  {"kImportSD2", "Import SD2..."},
	  {"kImportWOCE", "Import WOCE..."},
	  {"kImportSS", "Import Spreadsheet..."},
	  {"kExportSpreadsheet", "Export Spreadsheet..."},
	  {"kFilters", "Filters"},
	  {"kWindows", "Windows"},
	  {"kStationFilter", "Station Filter..."},
	  {"kObservationFilter", "Observation Filter..."},
	  {"kWindows", "Windows"},
	  {"kHelp", "Help..."},
	  {"kHelp2", "Help"},
	  {"kOpen", "Open..."},
	  {"kOpen2", "Open in New Data Window"},
	  {"kAddData", "Add Data..."},
	  {"kSave", "Save"},
	  {"kSaveAs", "Save As..."},
	  {"kQuit", "Quit"},
	  {"kExit", "Exit"},
	  {"kPlots", "Plots"},
	  {"kPropertyProperty", "Property-Property..."},
	  {"kLinePlot", "Line Plot..."},
	  {"kProfile", "Profile..."},
	  {"kAbout", "About Java OceanAtlas..."},
	  {"kParameter", "Parameter"},
	  {"kOptions", "Options..."},
	  {"kWindowName", "Window name:"},
	  {"kOffsetBy", "Offset by:"},
	  {"kSequence", "Sequence"},
	  {"kDistance", "Distance"},
	  {"kLatitude", "Latitude"},
	  {"kLongitude", "Longitude"},
	  {"kPlot", "Plot"},
	  {"kMap", "Map..."},
	  {"kPresetRegion", "Preset Region:"},
	  {"kRegion", "Projection/Region"},
	  {"kNorthAtlantic", "North Atlantic"},
	  {"kSouthAtlantic", "South Atlantic"},
	  {"kNorthPacific", "North Pacific"},
	  {"kSouthPacific", "South Pacific"},
	  {"kMediteranean", "Mediteranean"},
	  {"kIndian", "Indian"},
	  {"kArctic", "Arctic"},
	  {"kAntarctic", "Antarctic"},
	  {"kWorld1", "World (Left = 180W)"},
	  {"kWorld2", "World (Left = 20E)"},
	  {"kWorld3", "World (Left = 120E)"},
	  {"kWorld4", "World (Left = 60W)"},
	  {"kWorld", "World"},
	  {"kCustomRegion", "Custom Region"},
	  {"kProjection", "Projection:"},
	  {"kMapCenter", "Map center:"},
	  {"kMercator", "Mercator"},
	  {"kCylindrical", "Miller"},
	  {"kStereographic", "Stereographic"},
	  {"kMollweide", "Mollweide"},
	  {"kOrthographic", "Orthographic"},
	  {"kLambert", "Lambert Azimuthal Equal Area"},
	  {"kBathymetry", "Bathymetry"},
	  {"kStationAndSectionColor", "Station and section color"},
	  {"kLineColor", "Line color:"},
	  {"kSymbolColor", "Symbol color:"},
	  {"kBackgroundColor", "Background:"},
	  {"kCoastlineColor", "Coastline:"},
	  {"kGraticuleColor", "Graticule:"},
	  {"kRetainAspect", "Retain cartographic aspect when resizing"},
	  {"kLatSpacing", "Latitude Spacing (deg):"},
	  {"kLonSpacing", "Longitude Spacing (deg):"},
	  {"kMapGraticule", "Map graticule"},
	  {"kSpacing", "Spacing (deg):"},
	  {"kSymbolSize", "Symbol size:"},
	  {"kConnectStations", "Connect stations"},
	  {"kConnectStationsAcross", "Connect stations at section boundaries"},
	  {"kOptions", "Options"},
	  {"kColors", "Colors"},
	  {"kColorBars:", "Colorbars:"},
	  {"kXAxisParameter", "X-Axis Parameter:"},
	  {"kYAxisParameter", "Y-Axis Parameter:"},
	  {"kWindowName", "Window name:"},
	  {"kIncludeColorBar", "Include colorbar"},
	  {"kColor", "Color"},
	  {"kCoastline", "Coastline:"},
	  {"kNoCoast", "None"},
	  {"kCoarseRez", "Coarse"},
	  {"kFineRez", "Fine"},
	  {"kColorSchemes", "Styles:"},
	  {"kWhiteBackground", "White background"},
	  {"kBlackBackground", "Black background"},
	  {"kLegend", "Legend"},
	  {"kAxesLabelsColors", "Axes/Text:"},
	  {"kCalculations", "Calculations"},
	  {"kColor2", "Color:"},
	  {"kParameters", "Parameters..."},
	  {"kColorPaletteEditor", "Color Palette Editor..."},
	  {"kObservationCalculations", "Observation calculations"},
	  {"kTheta", "Theta (Deg. C)"},
	  {"kSigma0", "Sigma 0 (kg/m^2)"},
	  {"kSigma1", "Sigma 1 (kg/m^2)"},
	  {"kSigma2", "Sigma 2 (kg/m^2)"},
	  {"kSigma3", "Sigma 3 (kg/m^2)"},
	  {"kSigma4", "Sigma 4 (kg/m^2)"},
	  /*{"kTheta", "Theta (" + '\u00b2' + "C)"},
	  {"kSigma0", "Sigma 0 (kg/m" + '\u00b3' + ")"},
	  {"kSigma1", "Sigma 1 (kg/m" + '\u00b3' + ")"},
	  {"kSigma2", "Sigma 2 (kg/m" + '\u00b3' + ")"},
	  {"kSigma3", "Sigma 3 (kg/m" + '\u00b3' + ")"},
	  {"kSigma4", "Sigma 4 (kg/m" + '\u00b3' + ")"},*/
	  {"kSigmaRef", "Sigma, ref.="},
	  {"kSpecificVolumeAnomaly", "Specific volume anomaly (m^2/kg)"},
	  {"kSpiciness", "Spiciness (Jackett & McDougall)"},
	  {"kSpiciness2", "Spiciness (Flament)"},
	  {"kSoundVelocity", "Sound velocity (m/s)"},
	  {"kO2Sat", "O2 % saturation"},
	  {"kAOU", "AOU"},
	  {"kNO", "NO"},
	  {"kPO", "PO"},
	  {"kcStar", "C*"},
	  {"kVolumeToMass", "Volume->Mass Units (AOU/NO/PO/C*)"},
	  {"kAOU/NO/PO", "(AOU/NO/PO)"},
	  {"kHeatStorage", "Heat Storage"},
	  {"kAlphaBeta", "Alpha/Beta"},
	  {"kAlpha", "Alpha (thermal expansion)"},
	  {"kAlphaDeriv", "Alpha * dT/dz"},
	  {"kBeta", "Beta (saline contraction)"},
	  {"kBetaDeriv", "Beta * dS/dz"},
	  {"kBuoyancyFrequency", "Buoyancy frequency (Hz)"},
	  {"kEFolding", "e-folding length: "},
	  {"kMeters", "(m)"},
	  {"kN", "N"},
	  {"kNSq", "N^2"},
	  {"kFNSqG", "fN^2/g"},
	  {"kIntegralCalculations", "Integral calculations (reference = 0)"},
	  {"kAcousticTravelTime", "Acoustic travel time (sec)"},
	  {"kNetHeatContent", "Net heat content (10^9 J/m^2)"},
	  {"kPotentialEnergyAnomaly", "Potential energy anomaly (10^6 J/m^2)"},
	  {"kGeopotentialAnomaly", "Geopotential anomaly (J/m)"},
	  {"kColorPalettes", "Color palettes:"},
	  {"kPick", "Pick..."},
	  {"kBlend", "Blend"},
	  {"kSave", "Save..."},
	  {"kNew", "New..."},
	  {"kContourManager", "Contour Manager..."},
	  {"kColorbars", "Colorbars:"},
	  {"kApply", "Apply"},
	  {"kEdit", "Edit..."},
	  {"kDescription", "Description"},
	  {"kParameter2", "Parameter:"},
	  {"kTitle", "Title:"},
	  {"kStartValue", "Start value:"},
	  {"kEndValue", "End value:"},
	  {"kNumContours", "Number of contours:"},
	  {"kAssignFromTable", "Assign colors from color table"},
	  {"kBlendColors", "Blend colors"},
	  {"kAssignFromRainbow", "Rainbow"},
	  {"kAssignFromInvRainbow", "Inverse Rainbow"},
	  {"kStartColor", "Start color:"},
	  {"kAssignColors", "Assign colors:"},
	  {"kAcrossTable", "Across table"},
	  {"kDownTable", "Down table"},
	  {"kMiddleColor", "Middle color:"},
	  {"kEndColor", "End color:"},
	  {"kInitialShape", "Initial shape:"},
	  {"kColorAssignment", "Color Assignment"},
	  {"kCreate", "Create"},
	  {"kCreateCalculation", "Create Calculation"},
	  {"kPendingCalculations", "Pending calculations:"},
	  {"kColorPalettes", "Color Palettes:"},
	  {"kValue", "Value:"},
	  {"kValueEditor", "Value Editor"},
	  {"kCreateWithShape", "Create with shape:"},
	  {"kColorBarPreview", "Colorbar Preview"},
	  {"kDescription2", "Description:"},
	  {"kContours", "Contours"},
	  {"kValueEditorPreview", "Value Editor/Preview"},
	  {"kDelete", "Delete"},
	  {"kDone2", "Done"},
	  {"kDone", "Cancel"},
	  {"kMakeDefault", "Make Default"},
	  {"kMakeDefault...", "Make Default..."},
	  {"kLevels", "Levels"},
	  {"kNumLevels", "Number of levels"},
	  {"kFirstLevel", "First level:"},
	  {"kLastLevel", "Last level:"},
	  {"kLevelEditor", "Level editor"},
	  {"kInterpolationSurfaces", "Interpolation surfaces"},
	  {"kOverlayParameter", "Overlay Parameter"},
	  {"kSurfaceManager", "Surface Manager..."},
	  {"kResources", "Resources"},
	  {"kInterpolationSurfaces", "Interpolation surfaces"},
	  {"kExistingInterpolations", "Existing interpolations"},
	  {"kInterpolationName", "Interpolation name:"},
	  {"kInterpolate", "Interpolate"},
	  {"kVerticalInterpolations", "Vertical Interpolations..."},
	  {"kInterpolationDirection", "Interpolation direction"},
	  {"kInterpolationDirectioncolon", "Interpolation direction:"},
	  {"kIntegrationDirectioncolon", "Integration direction:"},
	  {"kReferenceLevel", "Reference Level"},
	  {"kReferenceLevel2", "Reference Level:"},
	  {"kTopDown", "Top down"},
	  {"kBottomUp", "Bottom up"},
	  {"kValueOf", "Value of"},
	  {"kStyle", "Contour Style"},
	  {"kContourLines", "Lines only"},
	  {"kFiledl", "Filled"},
	  {"kColorFillWContours", "Filled w/lines"},
	  {"kOffset", "Offset"},
	  {"kMarkers", "Markers"},
	  {"kNone", "None"},
	  {"kSurfaceLevels", "Surface levels"},
	  {"kObservations", "Observations"},
	  {"kColorLegend", "Color legend"},
	  {"kEnableBrowsing", "EnableBrowsing"},
	  {"kShowCrossSections", "Cross sections"},
	  {"kYAxisRange", "Y axis range:"},
	  {"kMinimum", "Minimum:"},
	  {"kMaximum", "Maximum:"},
	  {"kMinimum2", "Minimum"},
	  {"kMaximum2", "Maximum"},
	  {"kMin", "Min"},
	  {"kMax", "Max"},
	  {"kAutoscale", "Autoscale"},
	  {"kContour", "Contour..."},
	  {"kAdvContour", "Advanced Contour..."},
	  {"kOther", "Other"},
	  {"kBasedOn", "Based on:"},
	  {"kCreateAutoscaleColorbar", "Create autoscale colorbar"},
	  {"kShape", "Shape:"},
	  {"kUsing", "Using:"},
	  {"kBottles", "(bottles)"},
	  {"kPlotAxes", "Plot axes"},
	  {"kHorizontalInterpolation", "Horizontal interpolation"},
	  {"kVerticalInterpolation", "Vertical interpolation"},
	  {"kCasts", "(casts)"},
	  {"kDistanceColon", "Distance:"},
	  {"kMaxDistanceColon", "Maximum distance:"},
	  {"kMaxDistanceColon2", "Max. dist.:"},
	  {"kKM", "(km)"},
	  {"kConnectObservations", "Connect observations"},
	  {"kCustomParameter", "Custom Parameter..."},
    {"kForecastTS", "Model TS Relationship..."},
	  {"kCustomStnParameter", "Custom Station Parameter..."},
	  {"kParameterTransformations", "Parameter Transformations..."},
	  {"kTransformations", "Transformations"},
	  {"kConstant", "Constant:"},
	  {"kNewParameterName", "New parameter name:"},
	  {"kReverseWhenY", "Reverse when plotted as Y-axis parameter?"},
	  {"kParameter1", "Parameter 1:"},
	  {"kParameter2Colon", "Parameter 2:"},
	  {"kSV1", "Station Variable 1:"},
	  {"kSV2", "Station Variable 2:"},
	  {"kAdvancedOptions", "Advanced Options"},
	  {"kPlotAxes", "Plot axes"},
	  {"kYGrid", "Y Grid"},
	  {"kXGrid", "X Grid"},
	  {"kXAxis", "X Axis"},
	  {"kYAxis", "Y Axis"},
	  {"kIncrement", "Increment:"},
	  {"kNoMinorTicks", "# of minor ticks:"},
	  {"kUseDataMaxMin", "Use Data Max/Mins"},
	  {"kDataMaxMin", "Data Max/Min"},
	  {"kPlotSymbol", "Plot symbol:"},
	  {"kSymbol", "Symbol:"},
	  {"kSize", "Size:"},
	  {"kAxes", "Axes"},
	  {"kBlackBG", "Black background"},
	  {"kReverseStations", "Reverse stations"},
	  {"kMergeCasts", "Merge multiple casts at same station "},
	  {"kMergeSections", "Merge all stations into one section (creates new section)"},
	  {"kSortAllStns", "Re-order/Sort/Delete stations (creates new section)"},
	  {"kAmplitude", "Amplitude:"},
	  {"kTraceOffset", "Trace offset"},
	  {"kPixels", "(pixels)"},
	  {"kNMPerPixel", "(nm/pixel)"},
	  {"kLineWidthColon", "Line width:"},
	  {"kAxes", "Axes"},
	  {"kXAxisRange", "X Axis Range"},
	  {"kYAxisRange", "Y Axis Range"},
	  {"kAxes", "Axes"},
	  {"kCurrentObservation", "Current Observation"},
	  {"kEmpty", ""},
	  {"kCurrentStation", "Current Station"},
	  {"kIsopycnals", "Isopycnals"},
	  {"kReferencePressure", "Reference pressure:"},
	  {"kPressure", "Pressure:"},
	  {"kAnd", "And"},
	  {"kOr", "Or"},
	  {"kCondition1", "Condition 1"},
	  {"kCondition2", "Condition 2"},
	  {"kDisplayOptions", "Display options"},
	  {"kShowMatching", "Show only matching observations"},
	  {"kHighlight", "Highlight matching observation"},
	  {"kEnlargeSymbol", "Enlarge current symbol"},
	  {"kUseNewSymbols", "Contrasting symbol:"},
	  {"kLocationFilter", "Location Filter"},
	  {"kStationSelectionFilter", "Station/Section Filter"},
	  {"kIncludeStations", "Include stations"},
	  {"kExcludeStations", "Exclude stations"},
	  {"kMissingParameterFilter", "Missing Parameter Filter"},
	  {"kStationColors", "Station Colors"},
	  {"kIsoSurface", "Iso-surface value"},
	  {"kAssignedStnColors", "JOA-assigned section colors"},
	  {"kParameter:", "Parameter:"},
	  {"kColorMapping", "Color mapping:"},
	  {"kSurface", "Surface:"},
	  {"kMapColors", "Map Colors"},
	  {"kColors:", "Colors:"},
	  {"kBottomUpSearch", "Bottom up search"},
	  {"kOverlayContours", "Overlay contours:"},
	  {"kPlotEvery", "Plot every:"},
	  {"kLabelEvery", "Label every:"},
	  {"kContours", "(nd, rd, th) contour"},
	  {"kColorLines", "Color contour lines"},
	  {"kContourOptions", "Options..."},
	  {"kDefault", "Default"},
	  {"kGridColor", "Grid color"},
	  {"kInterpOptions", "Interpolation Options..."},
	  {"kPrint", "Print..."},
	  {"kConnectLineWidth", "Connect observations line width: "},
	  {"kLineWidth", "Line width"},
	  {"kMissingValColor", "Missing value color"},
	  {"kPlotBGColor", "Plot background color"},
	  {"kPlotInteriorColor", "Plot interior color"},
	  {"kSectionWidth", "Section width:"},
	  {"kSelectedStations", "Selected Stations"},
	  {"kStoN", "S->N"},
	  {"kStoNSpecial", "S->N (required for latitude offset)"},
	  {"kNtoS", "N->S"},
	  {"kEtoW", "E->W"},
	  {"kWtoE", "W->E"},
	  {"kWtoESpecial", "W->E (required for longitude offset)"},
	  {"kStnDsc", "Stn. number (dsc)"},
	  {"kStnAsc", "Stn. number (asc)"},
	  {"kDateDsc", "Date (dsc)"},
	  {"kDateAsc", "Date (asc)"},
	  {"kSorting", "Sorting"},
	  {"kNewSectionName", "New section name:"},
	  {"kNewSection", "New section:"},
	  {"kSort", "Sort"},
	  {"kLineSpacing", "Line spacing:"},
	  {"kNorthPole", "North Pole"},
	  {"kSouthPole", "South Pole"},
	  {"kCentralAtlantic", "Central Atlantic"},
	  {"kCentralPacific", "Central Pacific"},
	  {"kDistanceLegend", "Distance (km)"},
	  {"kLatitudeLegend", "Latitude"},
	  {"kLongitudeLegend", "Longitude"},
	  {"kSequenceLegend", "Station Ordinal"},
	  {"kSectionManager", "File Manager..."},
	  {"kActions", "Actions"},
	  {"kActions2", "Actions:"},
	  {"kReverseStations", "Reverse stations"},
	  {"kProperties", "Properties..."},
	  {"kExportKML", "Export KML..."},
	  {"kNews", "News"},
	  {"kStationSelection", "Station Selection"},
	  {"kSection", "Section:"},
	  {"kStationNumber", "Station number:"},
	  {"kStationNumber2", "Station number"},
	  {"kCastNumber", "Cast number:"},
	  {"kLatitudeColon", "Latitude:"},
	  {"kShipCode", "Platform:"},
	  {"kDate", "Date:"},
	  {"kLongitudeColon", "Longitude:"},
	  {"kBottom", "Bottom:"},
	  {"kMM", "MM:"},
	  {"kDD", "DD:"},
	  {"kYYYY", "YYYY:"},
	  {"kHH", "HH"},
	  {"kMM.M", "MM.M:"},
	  {"kXAxisScale", "X Axis Scale"},
	  {"kCustom", "Custom:"},
	  {"kkm/cm", "(km/pix)"},
	  {"kdeg/cm", "(deg/pix)"},
	  {"kstn/cm", "(stns/pix)"},
	  {"kInterpolationLevel", "Interpolation Level"},
	  {"kMissingValueOptions", "Missing Value Options"},
	  {"kReferencedTo", "Reference Interpolation To:"},
	  {"kMeanCast", "Mean Cast (computed from selected stations)"},
	  {"kMeanCast2", "Mean Cast (from existing data file/window)"},
	  {"kMeanCast3", "Mean Cast..."},
	  {"kLon", "Lon:"},
	  {"kLat", "Lat:"},
	  {"kUnits", "Units:"},
	  {"kDisplayUnits", "Display units in data window"},
	  {"kName", "Name:"},
	  {"kPolar", "Polar"},
	  {"kReverseY", "Reverse Y"},
	  {"kReverseYAxis", "Reverse Y axis"},
	  {"kFileComments", "File Comments"},
	  {"kImport", "Import"},
	  {"kPOA", "Power OceanAtlas..."},
	  {"kSS", "Spreadsheet (TSV)..."},
	  {"kSD2", "SD2..."},
	  {"kSD3", "SD3..."},
	  {"kWOCE2", "WOCE Import"},
	  {"kWOCE", "WOCE Hydrographic..."},
	  {"kWOCEQC", "WOCE"},
	  {"kWOCEQCFLag", "WOCE: _FLAG_W"},
	  {"kIGOSSQCFLag", "IGOSS: _FLAG_I"},
	  {"kPixPerKM", "(pixel/km)"},
	  {"kNoDecimation", "No decimation"},
	  {"kConstant", "Constant"},
	  {"kEvery", "every"},
	  {"kDB", "(db)"},
	  {"kDate", "Date:"},
	  {"kStandardLevels", "Standard levels:"},
	  {"kGeneral", "General"},
	  {"kCTDDecimation", "CTD Decimation"},
	  {"kWoceImport", "WOCE Import"},
	  {"kCustomDotDotDot", "Custom..."},
	  {"kExportNetCDF", "Export netCDF Section..."},
	  {"kConvertTemp", "Convert temperatures from ITS90 to IPTS68 (required for density calculations)"},
	  {"kConvertMassToVol", "Convert from mass to volume units"},
	  {"kReplaceMsg1", "Replace with missing value when parameter quality code is:"},
	  {"kReplQB3", "3 (Questionable value)"},
	  {"kReplQB7", "7 (Manual CFC)"},
	  {"kReplQB4", "4 (Bad measurement)"},
	  {"kReplQB8", "8 (Irregular CFC)"},
	  {"kMergeCasts", "Merge multiple casts at same station (creates new section)"},
	  {"kReplaceAllBottleParams", "Set ALL bottle parameters missing when bottle quality code=4"},
	  {"kReplaceAllGasParams", "Set gas parameters missing where bottle quality code=3 and bottle oxygen quality code=4"},
	  {"kDisplayQC", "Display quality codes in data window"},
	  {"kColorByDefault", "Color symbols by default color"},
	  {"kColorByQC", "Color symbols by bottle quality code"},
	  {"kColorByParamPres", "Color symbols by presence of parameter:"},
	  {"kIsobaths", "Isobaths"},
	  {"kLockRgn", "Lock region"},
	  {"kColorFill", "Color fill"},
	  {"kColorFillBathy", "Color Fill Bathymetry"},
	  {"kResolution", "Resolution:"},
	  {"kContrastColor", "Contrasting color:"},
	  {"kSaveGraphic", "Save plot as GIF..."},
	  {"kSaveData", "Save data..."},
	  {"kAssignColorsOnly", "Assign Colors Only"},
	  {"kPlotOlnyCurrStn", "Plot current station only     "},
	  {"kPlotAllStns", "Plot all stations     "},
	  {"kAccumulateStns", "Paint stations     "},
	  {"kPlotUsingCB", "Color symbols by current colorbar"},
	  {"kPlotUsingCLC", "Color symbols by \"Connect line color\""},
	  {"kPlotUsingNothing", "Plot symbols are black"},
	  {"kBrowse", "Bowse collections..."},
	  {"kView", "View"},
	  {"kZoom", "Zoom"},
	  {"kExportEPICPtr", "Export EPIC Pointer File..."},
	  {"kExportStnCalcs", "Export Station Parameters..."},
	  {"kSaveSettings", "Save Settings..."},
	  {"kReadSettings", "Read Settings..."},
	  {"kSaveModel", "Save Model..."},
	  {"kReadModel", "Read Model..."},
	  {"kLoad", "Load..."},
	  {"kSaveInterpolation", "Save Grid Values..."},
	  {"kDelimiter", "Delimiter"},
	  {"kTab", "Tab"},
	  {"kComma", "Comma"},
	  {"kUDDelimiter", "User Defined:"},
	  {"kMissingValue", "Missing Value"},
	  {"kDefaultMissing", "JOA Default Missing Value (-99)"},
	  {"kCustomMissingValue", "User Defined Missing Value:"},
	  {"kStationCalculation", "Station Parameters"},
	  {"kStationCalculation2", "Station Parameters:"},
	  {"kWRT", "With respect to:"},
	  {"kSurfaceAsMin", "Use shallowest observation if needed"},
	  {"kBottomAsMax", "Use deepest observation if needed"},
	  {"kComputeWeightedMean", "Compute weighted mean"},
	  {"kSurfaceMethod", "Surface method"},
	  {"kStartDepthOfSurface", "Minimum depth:"},
	  {"kMaxDepthOfSurface", "Maximum depth:"},
	  {"kDepthOfDifference", "Starting depth of difference calculation:"},
	  {"kDepthOfSlope", "Starting depth of slope calculation:"},
	  {"kSlopeMethod", "Slope method"},
	  {"kTolerance", "Tolerance:"},
	  {"kIntegrand", "Integrand:"},
	  {"kIntegration", "Integration"},
	  {"kMixedLayer", "Depth of Mixed Layer"},
	  {"kTestParameter", "Test Parameter"},
	  {"kDifferenceMethod", "Difference method"},
	  {"kStnPlot", "Station Value Plot..."},
	  {"kStnXYPlot", "Station Value XY Plot..."},
	  {"kTranslateQC", "Translate WOCE quality codes to IGOSS"},
	  {"kMapTab1", "General Settings"},
	  {"kMapTab2", "Bathymetry"},
	  {"kMapTab3", "Station Colors"},
	  {"kContourTab1", "Basic"},
	  {"kContourTab2", "Advanced"},
	  {"kContourTab3", "Overlay Contour"},
	  {"kContourTab3a", "Overlay Contours"},
	  {"kContourTab4", "Primary Contours"},
	  {"kMixedSearch", "Search down for min and up for max"},
	  {"kInterpMissing", "Interpolate missing values"},
	  {"kShowNdedit", "Show NdEdit"},
	  {"kWindows", "Windows"},
	  {"kConnectLineColor", "Connect line color"},
	  {"kTestParameter", "Test Parameter"},
	  {"kParameterOrder", "Parameter order"},
	  {"kXAxes", "X Axes:"},
	  {"kSelectFilter", "Select saved filter:"},
	  {"kMapColor", "Map color:"},
	  {"kShowSectionEditor", "Section Editor..."},
	  {"kPlotSectionLabels", "Plot section labels"},
	  {"kRemove", "Remove"},
	  {"kClearAll", "Clear All"},
	  {"kClose", "Close"},
	  {"kPlotLabels", "Plot graticule labels"},
	  {"kLabels", "Labels:"},
	  {"kAutomatic", "Automatic"},
	  {"kBathymetryFiles", "Bathymetry files:"},
	  {"kFileProperties", "File Properties..."},
	  {"kParamProperties", "Parameter Properties..."},
	  {"kTranslateParamNames", "Translate parameter names on read and import"},
	  {"kJOAPreferences", "JOA Preferences..."},
	  {"kIncludeBrowser", "Observation browser"},
	  {"kDefaultAutoscaleColorScheme", "Default autoscale color scheme:"},
	  {"kMergeObservations", "Average observed values at same pressure"},
	  {"kGratLabels", "Graticule Labels"},
	  {"kTranslateOrigin", "Translate origin:"},
	  {"kOpenDODS", "Open DODS..."},
	  {"kBlueLegend", "Out-Of-Range Max"},
	  {"kYellowLegend", "Out-Of-Range Min"},
	  {"kRedLegend", "Out-Of-Range Max and Min"},
	  {"kBrowserSymbol", "Browsing cursor symbol:"},
	  {"kStationSymbol", "Station symbol:"},
	  {"kNumCycles", "Number of cycles"},
	  {"kTwoColorTransition", "Two color transition"},
	  {"kThreeColorTransition", "Three color transition"},
	  {"kStationMetadata", "Station Metadata:"},
	  {"kBaseColorbar", "Base colorbar on: "},
	  {"kParameter3", "Measured parameter:"},
	  {"kDateTime", "Date-Time"},
	  {"kGeographicFormat", "Geographic format:"},
	  {"kDateFormat", "Date format:"},
	  {"kDateTimeMonth", "Month"},
	  {"kJan", "Jan"},
	  {"kFeb", "Feb"},
	  {"kMar", "Mar"},
	  {"kApr", "Apr"},
	  {"kMay", "May"},
	  {"kJun", "Jun"},
	  {"kJul", "Jul"},
	  {"kAug", "Aug"},
	  {"kSep", "Sep"},
	  {"kOct", "Oct"},
	  {"kNov", "Nov"},
	  {"kDec", "Dec"},
	  {"kStnValStnColors", "Station calculation values"},
	  {"kMetadataStnColors", "Metadata"},
	  {"kMDColors:", "Metadata colorbars:"},
	  {"kAtMin", " at minimum"},
	  {"kAtMax", " at maximum"},
	  {"kSubjectTo", " Subject to active observation filter"},
	  {"kOnwspaces", " on "},
	  {"kStnColorsEqual", "Station colors: "},
	  {"kStartingIsoValue", "Initial surface value:"},
	  {"kMinSurf", "Min surface only "},
	  {"kMaxSurf", "Max surface only"},
	  {"kPlotWindowBGColor", "Plot window background color"},
	  {"kEnhancementOptions", "Enhancement"},
	  {"kPlotEnhancementsLast", "Plot enhanced values last"},
	  {"kEnlargeSymbolBy", "Enlarge current symbol by"},
	  {"kZAxisRange", "Z Axis Range"},
	  {"kNeutralDensityWUnits", "Neutral density (kg/m^2)"},
	  {"kIncludeErrorEstimates", "Include error estimates"},
	  {"kNeutralSurface", "Neutral Surface"},
	  {"kSalinityOnNS", "Salinity on surface"},
	  {"kTemperatureOnNS", "Temperature on surface"},
	  {"kPressureOnNS", "Pressure of surface"},
	  {"kNeutralDensity", "Neutral Density (Gamma)"},
	  {"kNeutralSurfaceGamma", "Gamma of neutral surface: "},
	  {"kCalculationSelection", "Select Calculations"},
	  {"kWindowSelection", "Select Plots"},
	  {"kSaveWorkSpaceAs", "Save Work Space As..."},
	  {"kFillEdges", "Fill edges"},
	  {"kClipExtrapolation", "Restrict extrapolation to data range"},
	  {"kComputeMeanCast", "Compute mean cast"},
	  {"kIncludeStatistics", "Include statistics"},
	  {"kInterpolationSurface", "Interpolation surface:"},
	  {"kNoneInterpolation", "No missing value interpolation"},
	  {"kLocalInterpolation", "Vertical interpolation. If an observation bounding a standard level is missing:"},
	  {"kFarFieldInterpolation", "Far-field interpolation (horizontal interpolation to fill missing standard levels) "},
	  {"kMaxLocalInterpDistance", "Look a max. of"},
	  {"kObsAboveBelowStdLevel", "observations above/below standard level for a non-missing observation."},
	  {"kIfObservedNotFound", "If observed value is not found within "},
	  {"kUseInterpolated", "use interpolated values up to"},
	  {"kStationsLeftAndRight", "stations to the left and right"},
	  {"kStandardLevels2", "standard levels"},
	  {"kJOADefaultMissing", "-99 (JOA Default)"},
	  {"kWOCEDefaultMissing", "-999.0 (WOCE Default)"},
	  {"kEPICDefaultMissing", "1e35 (EPIC Default)"},
	  {"kCustomMissing", "User defined:"},
	  {"kMissingValueSelection", "Missing Value Selection"},
	  {"kSpaceMissing", "Space Character"},
	  {"kTabDelim", "Tab (JOA Default)"},
	  {"kCommaDelim", "Comma"},
	  {"kSpaceDelim", "Space Character (output only)"},
	  {"kDelimiterSelection", "Field Delimiter Selection"},
	  {"kFilePreview", "File Preview"},
	  {"kStationCalcResults", "Station Parameters:"},
	  {"kLockPlot", "Lock/Unlock this plot window"},
	  {"kFonts", "Fonts"},
	  {"kAxisValuesLabels", "Axis values labels:"},
	  {"kAxisLabels", "Axis labels:"},
    {"kIsopycnalLabels", "Contour/Isopycnal labels:"},
	  {"kJOANews", "JOA News..."},
	  {"kNdEditNews", "NdEdit News..."},
	  {"kNdEdit", "NdEdit"},
	  {"kAboutNdEdit", "About NdEdit..."},
	  {"kSystemProperties", "System Properties..."},
	  {"kSaveStyle", "Save Style..."},
	  {"kLoadStyle", "Load Style..."},
	  {"kPlotTitleLabels", "Plot title:"},
	  {"kPlotTitles", "Plot title:"},
	  {"kPlotTitles2", "Plot titles in plot windows"},
	  {"kColorBarLabels", "Colorbar labels:"},
	  {"kSetAllFonts", "Set individual settings to:"},
	  {"kMapLabels", "Map graticule labels:"},
	  {"kPageSetup", "Page Setup..."},
	  {"kInterpolation", "Interpolation"},
	  {"kOntoSurface", "Onto Surface:"},
	  {"kAtValue", "At value:"},
	  {"kAtSurface", "At surface"},
	  {"kAtBottom", "At bottom"},
	  {"kDepthLimit", "Depth limit:"},
	  {"kSearchDirection", "Search direction:"},
	  {"kUseDeepestIfBottomIsMissing", "Use deepest observation if bottom is missing"},
	  {"kCalcMLD", "Mixed Layer Depth..."},
	  {"kCalcInterp", "Interpolation..."},
	  {"kCalcInteg", "Integration..."},
	  {"kCalcNS", "Neutral Surface..."},
	  {"kSurfaceValue", "Surface Value"},
	  {"kLocalInterpolation2", "Vertical interpolation"},
	  {"kObsAboveBelowStdLevel2", "Max number observations"},
	  {"kCalcExtrema", "Extrema..."},
	  {"kEntireRange", "Entire range"},
	  {"kInRange", "In range:"},
	  {"kOtherParams", "Also Include:"},
	  {"kOn", "On:"},
	  {"kDefaultSymbols", "Station locations are plotted with the symbol style and size specified in the \"General Settings\" tab of this dialog. " +
			      "Station location symbols are colored according the automatic colors assigned by JOA (or custom colors assigned in the File Properties dialog.)"},
	  {"kOverEachProfile", "Over each profile"},
	  {"kMinimumValue", "Minimum value of variable"},
	  {"kMaximumValue", "Maximum value of variable"},
	  {"kDepthMinimumValue", "Depth of minimum value of variable"},
	  {"kDepthMaximumValue", "Depth of maximum value of variable"},
	  {"kCalcAverage", "Average of values of variable"},
	  {"kNumberNonMissing", "Number of non-missing values of variable"},
	  {"kMaxDepthofNonMissingValue", "Maximum depth of non-missing value of observed variable"},
	  {"kMinDepthofNonMissingValue", "Minimum depth of non-missing value of observed variable"},
	  {"kCalcStnStats", "Station Statistics..."},
	  {"kEditPlot", "Edit Plot Settings..."},
	  {"kOpenDapper", "Browse Dapper..."},
	  {"kPlotStationLabels", "Plot station labels"},
	  {"kInterpMissingMaxDist", "Max number observations:"},
	  {"kMapStnLabels", "Map station labels:"},
	  {"kLabelOffset", "Offset:"},
	  {"kLabelAngle", "Angle:"},
	  {"kLabelPrec", "Precision:"},
	  {"kDegrees", "(degs)"},
	  {"kDegrees2", "degs"},
	  {"kAddBottom", "Add ocean bottom from bathymetry file:"},
	  {"kContours2", "Contours:"},
	  {"kBlackContours", "Black contours"},
	  {"kWhiteContours", "White contours"},
	  {"kCustomSingleColor", "Custom color:"},
	  {"kColorsFromColorBar", "Colors from colorbar"},
	  {"kCreateAutoscaleContours", "Create autoscale contours"},
	  {"kAxesScales", "Axes Scales"},
	  {"kPrimaryContours", "Primary Contours"},
	  {"kOverlayContours", "Overlay Contours"},
	  {"kPlotBottom", "Plot bottom"},
	  {"kXSecValues", "Contour cross section values:"},
	  {"kXSecLabels", "Contour cross section labels:"},
	  {"kSectionCalculations", "Section Calculations"},
	  {"kSectionDifference", "Combine Sections..."},
	  {"kRegridAtoB", "Regrid A to B                       "},
	  {"kRegridBtoA", "Regrid B to A                       "},
	  {"kRegridToUnion", "Regrid To A Union B"},
	  {"kRegridUsing", "Regrid Using"},
	  {"kFinalGrid", "Final Grid"},
	  {"kSectionA", "Section A:"},
	  {"kSectionB", "Section B:"},
	    { "kVerticalRegridding", "Vertical Regridding"},
	  {"kHorizontalRegridding", "Horizontal Regridding"},
	  {"kLogFileError", "Log File Error"},
	  {"kCouldntCreateLogFile", "Could not create log file!"},
	  {"kRenameSection", "Rename Section"},
	  {"kBaseLayer", "Base Layer: "},
	  {"kOverlayLayer", "   Overlay: "},
	  {"kTime", "Time"},
	  {"kPixPerDay", "(pixels/day)"},
	  {"kAddedData", "You have created a custom dataset by joining two or more files." + "\n" + "Save before closing?"},
	  {"kCreatedByUser", "You have created a custom dataset from other open datasets." + "\n" + "Save before closing?"},
	  {"kIsCollection", "You have created a collection of profiles that has never been saved." + "\n" + "Save before closing?"},
	  {"kEditedByUser", "You have made changes to an existing dataset." + "\n" + "Save before closing?"},
	  {"kCantEdit", "Can't Edit"},
	  {"kRevert", "Revert"},
	  {"kSelectAll", "Select All"},
	  {"kContourGradient", "Contour Gradient..."},
	  {"kFluxParameter", "Flux Parameter"},
	  {"kGeostrophicVelocity", "Geostrophic Velocity"},
	  {"kIntegrate", "Integrate"},
	  {"kFluxOrTransport", "Flux Or Transport"},
	  {"kLeftToRight", "Left To Right"},
	  {"kRightToLeft", "Right To Left"},
	  {"kUp", "Up"},
	  {"kNoContours", "No Contours"},
	  {"kFilterByParameter", "Filter observations by missing parameters (creates new section)"},
	  {"kBottleFilter", "Parameter Filter..."},
	  {"kFromEtopo", "From Etopo file:"},
	  {"kUserDefined", "User defined:"},
	  {"kmBelowLastObservation", "m below deepest observation"},
	  {"kApplyToAll", "Change all values"},
	  {"kApplyToMissing", "Change only missing values"},
	  {"kGrid", "Grid:"},
	  {"kGridSettings", "Grid Settings"},
	  {"kMaskCoast", "Mask coast"},
	  {"kMaskBottom", "Mask bottom"},
	  {"kGridDimensions", "Grid dimensions: "},
	  {"kInterpTension", "Interpolation tension:"},
	  {"kNumGridSpaces", "Number grid spaces:"},
	  {"kNoContoursL", "No Contours"},
	  {"kMapTab4", "Overlay Contours"},
	  {"kBottleSalinity", "Bottle Salinity"},
	  {"kCTDSalinity", "CTD Salinity"},
	  {"kDontSubstitute", "Don't Substitute"},
	  {"kVarToUseForSalt", "Variable To Use For Salinity:"},
	  {"kSubstitution", "Substitution if missing:"},
	  {"kBottleO2", "Bottle Oxygen"},
	  {"kCTDO2", "CTD Oxygen"},
	  {"kVarToUseForO2", "Variable To Use For Oxygen:"},
	  {"kParameterSubstitutions", "Parameter Substitutions"},
	  {"kWODSelect", "WOD Select Import Options"},
	  {"kIsoValue", "Surface Value:"},
	  {"kWOCEExchange", "Export WOCE Exchange File..."},
	  {"kMerge", "Merge..."},
	  {"kAutoDelim", "Automatic (tabs, comma, white space)"},
	  {"kTabComma", "Tabs and commas"},
	  {"kWhiteSpace", "White space"},
	  {"kNumToSkip", "Skip lines at beginning:"},
	  {"kUnitsLineNumber", "Units line number:"},
	  {"kHeaderLineNumber", "Header line number:"},
	  {"kSettings", "Settings"},
	  {"kFileSettings", "File Settings"},
	  {"kPreviewSettings", "Preview Settings"},
	  {"kCommentLines", "Comment lines start with:"},
	  {"kFuture", "Future"},
	  {"kRefresh", "Refresh"},
	  {"kRefreshPreview", "Refresh Preview"},
	  {"kOpenNewFile", "Open..."},
	   {"kSaveParsedFile", "Save Preview as..."},
	  {"kFieldDelimiter", "Field Delimiter:"},
	  {"kMissingValueEncoded", "Missing Value Encoded as:"},
	  {"kNext", "Next ->"},
	  {"kPrevious", "<- Previous"},
	  {"kExport", "Export..."},
	  {"kRecode", "Recode..."},
	  {"kMatchCriteria", "Match Criteria"},
	   {"kMergeRules", "Merge Rules"},
	   {"kMergeTo", "Merge To"},
	   {"kMergeMissingParameters", "Merge parameters not in destination file"},
	   {"kMergeSelectedParameters", "Merge selected parameters:"},
	   {"kMergeAllMatchingParameters", "Merge all matching parameters"},
	   {"kReplaceMissingParameters", "Replace parameters values in destination file"},
	   {"kReplaceSelectedParameters", "Replace selected parameters:"},
	   {"kReplaceAllMatchingParameters", "Replace all matching parameters"},

	   {"kClearLog", "Clear Log"},
	   {"kSaveLog", "Save Log..."},
	   {"kMergeLog", "Merge Log"},
	  {"kMatchFirst", "Match first:"},
	  {"kMatchSecond", "Match second:"},
	  {"kMatchThird", "Match third:"},
	  {"kRecodeValues", "Recode Values..."},
	  {"kRecodeParameter1", "Recode Parameter:"},
	  {"kRecodeExistingParameter", "Recode existing parameter (cannot be undone)"},
	  {"kRecodeQC", "Recode quality code for matching observations as:"},
//	  {"kDatabaseSetup", "Database Setup"},
//	  {"kDatabaseCalculations", "Database Calculations"},
//	  {"kDBDefaultDir", "Directory for saved databases:"},
	  {"kBrowse2", "Browse..."},
	  {"kSelect", "Select"},
	  {"kSelectDirectory", "Select Directory"},
	  {"kDBComment", "Comment:"},
	  {"kDBDir", "Location:"},
	  {"kEnterPassword", "Database server password:"},
	  {"kQueryResults", "Query Results for "},
	  {"kEnterServerPassword", "Enter Server Password:"},
//	  {"kDBURI", "Database URI:"},
//	  {"kDBPort", "Database port:"},
//	  {"kDBUserName", "User name:"},
//	  {"kDBPassword", "Password:"},
//	  {"kDBName", "Database Name:"},
	  {"kMinimumValue", "Minimum value of observed variable"},
	  {"kMaximumValue", "Maximum value of observed variable"},
	  {"kDepthMinimumValue", "Depth of minimum value of observed variable"},
	  {"kDepthMaximumValue", "Depth of maximum value of observed variable"},
	  {"kCalcAverage", "Average of values of observed variable"},
	  {"kNumberNonMissing", "Number of non-missing values of observed variable"},
	  {"kProfiles", "Profiles"},
	  {"kApplyToUserCalcs", "Apply built-in calculations to user-defined variables"},
//	  {"kCreateDB", "Create Database..."},
	  {"kMaxDepthofNonMissingValue", "Maximum depth of non-missing value of observed variable"},
	  {"kMinDepthofNonMissingValue", "Minimum depth of non-missing value of observed variable"},
	  {"kConvertDepth", "Convert depth in meters to decibars"},
	  {"kShowDebugMessagesInConsole", "Show debug messages in console"},
//	  {"kBuildDatabase", "Build Database..."},
	  {"kOpenDataWindow", "Open Data Window"},
	  {"kDBorFV", "Profiles downloaded from Dapper can be used to construct a new database or opened into a new JOA data window."},
	  {"kJOAAlert", "Dapper Data Destination"},
//	  {"kMaintainDatabase", "Maintain Databases..."},
//	  {"kCurrentDatabases", "Current Databases"},
	  {"kMoreInfo", "More Info..."},
//	  {"kDropDatabase", "Drop Database(s)..."},
//	  {"kMaintainDatabases2", "Maintain Databases"},
	  {"kResults", "Results"},
	  {"kSaveAsXMLPtr", "Save As XML Pointer File..."},
	  {"kMakeDefaults", "Make Defaults"},
	  {"kFirst", "First:"},
	  {"kSecond", "Second:"},
	  {"kThird", "Third:"},

	  {"kQCStandard", "Quality Code Standard:"},
	  {"kIGOSS", "IGOSS"},
	  {"kUnknown", "Unknown"},
	  {"kFillValue", "Fill value:"},
	  {"kAppendFile", "Append File..."},
	  {"kNAMissing", "NA"},
	  {"kNaN", "NaN (Not A Number)"},
	  {"kAllText", "All log messages (slowest)"},
	  {"kErrorsOnly", "Error messages only"},
	  {"kNoOutput", "No Output (Fastest)"},
	  {"kLogFilter", "Log Filter:"},
	  {"kX", "X:"},
	  {"kY", "Y:"},
	  {"kZGridInterpolation", "Objective Analysis"},
	  {"kPadFieldsWithBlanks", "Pad fields with blanks"},
	  {"kQCIdent", "QC Parameters have suffix:"},
	  {"kCreateNewSection", "Create new section"},
	  {"kNewName", "New section name:"},
	  {"kCloneSection", "Clone section (creates new section)"},
	  {"kOptimizedSearch", "Optimized search"},
	  {"kPrecision", "Prec:"},
	  {"kFeatureManagement", "Feature Management"},
	  {"kXAxisLabels", "X Axis Labels"},
	  {"kOffsetParameter", "Offset Parameter"},
	  {"kStationNumberAndCast", "Stn. Number and Cast"},
	  {"kSkip", "Skip:"},
	  {"kDapperPrefs", "Dapper"},
	  {"kCalcWindSpeed", "Calculate Wind Speed and Direction..."},
	  {"kUComponent", "u Component:"},
	  {"kVComponent", "v Component:"},
	  {"kNewSpeedParameterName", "Speed parameter name:"},
	  {"kSpeedUnits", "Speed units:"},
	  {"kDirectionParameterName", "Direction parameter name:"},
	  {"kAssignTS", "Assign missing salinities from TS relationship"},
	  {"kEnterTSModel", "Enter TS Model..."},
	  {"kRestrictAssignment", "Restrict assignment of salinities to the range:"},
	  {"kStnVariableName", "Station variable name:"},
	  {"kGenName", "Generate Name"},
	  {"kBestModel", "Allow JOA to pick best model with selected independent variables"},
	  {"kSingleVariableLR", "Single variable linear regression"},
	  {"kMultivariableLR", "Multivariable linear regression with selected independent variables"},
	  {"kSingleVariablePR", "Single variable polynomial regression"},
	  {"kTemperature", "Temperature"},
	  {"kSquaredTemperature", "Squared temperature"},
	  {"kLonxLat", "Lon x Lat"},
	  {"kComputeModel", "Compute Model"},
	  {"kModelDescrip", "Description of Saved Model"},
	  {"kModel", "Model"},
	  {"kIndependentVariables", "Independent Variables"},
	  {"kRespectActiveJOAFilters", "Respect active JOA filters"},
	  {"kMapPtrToolTipText", "Browse stations: single click," + "\n" +
	              " Edit map: double click, " + "\n" +
	              " Zoom map: drag rectangle"},
	  {"kHandToolTipText", "Select stations: single click," + "\n" +
		                     " Extend station selection: shift click," + "\n" +
		              			 " Select multiple stations: drag rectangle," + "\n" +
		              			 " Extend selection: shift-drag rectangle"},
	  {"kSectionToolTipText", "Select stations with section tool: " + "\n" +
		              				  " Start/end segment: single click," + "\n" +
		              				 	" End last segment: double click," + "\n" +
		              				 	" (hold shift to add to existing selection)"},
	  {"kPolygonToolTipText", "Select stations with polygon tool: " + "\n" +
			              				  " Start/end segment: single click," + "\n" +
	 	                          " End last segment: double click," +
			              				 	" (hold shift to add to existing selection)"},
	  {"kSectionWidthToolTipText", "Width of section tool in km"},
	  {"kLocalInterpHelp", "Use vertical interpolation to fill missing observations."},
	  {"kLocalInterpHelp", "Use vertical interpolation to fill missing observations."},
	  {"kLocalInterpHelp", "Use vertical interpolation to fill missing observations."},
	  {"kLocalInterpHelp", "Use vertical interpolation to fill missing observations."},
	  {"kFFInterpHelp", "Use horizontal interpolation to fill missing standard levels."},
	  {"kParamFilterHelp", "Exclude stations " +
				    "\n" +
				    "missing observations " +
				    "\n" +
				    "of selected parameters " +
				    "\n" +
				    "(select one or more.)"},

	  {"kBottleFilterHelp", " Remove bottles " +
				    "\n" +
				    "missing observations " +
				    "\n" +
				    "of selected parameters " +
				    "\n" +
				    "(select one or more.)"},

	  {"kDifferenceHelp",
				     "Difference Method:  The mixed layer is defined as the depth where the " + "\n" +
				     "difference between the value of the parameter and the value of parameter " + "\n" +
				     "at the specified depth is greater than the specified tolerance." + "\n"},

	  {"kSurfaceHelp",
				     "Surface Method: JOA first computes a surface layer by computing the mean " + "\n" +
				     "of the selected parameter from the surface (or shallowest observation) " + "\n" +
				     "to the maximum depth specified. The mixed layer is defined as the " + "\n" +
				     " depth where the difference between the value of the parameter " + "\n" +
				     "and the value of the surface layer is greater than the specified tolerance." + "\n"},

	  {"kSlopeHelp",
				     "Slope Method: The mixed layer is defined as the depth where the " + "\n" +
				     "difference in the gradient (slope) of the selected parameter is " + "\n" +
				     "greater than the specified tolerance." + "\n"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kFuture", "foobar"},
				     {"kReverseSTip", "Create colorbar with reverse s-curve relationship from min to max values. Contours are closely spaced in the middle of the range of values."},
				     {"kDecreasingExpTip", "Create colorbar with decreasing exponential relationship from max to min values. Contour spacing decreases as value increases."},
				     {"kIncreasingExpTip", "Create colorbar with increasing exponential relationship from min to max value of parameter. Contour spacing increases as value increases."},
				     {"kLinearTip", "Create colorbar with linear relationship from min to max value of parameter. Contours are evenly spaced."},
				     {"kSurfReverseSTip", "Create surface with reverse s-curve relationship from min to max values. Surfaces are closely spaced in the middle of the range of values."},
				     {"kSurfDecreasingExpTip", "Create surface with decreasing exponential relationship from max to min values. Surface spacing decreases as value increases."},
				     {"kSurfIncreasingExpTip", "Create surface with increasing exponential relationship from min to max value of parameter. Surface spacing increases as value increases."},
				     {"kSurfLinearTip", "Create surface with linear relationship from min to max value of parameter. Surfaces are evenly spaced."}
  };
}
