// Generated by Together
package ndEdit.filters.simple;

 import ndEdit.*;
 import ndEdit.filters.*;
import gov.noaa.pmel.util.GeoDate;


/** @stereotype Strategy*/
public class TimeFilter {

  //private SemaphoreResults_Event lnkUnnamed;
  PointerCollection pc;
  double begValue, endValue;
  double[] arr1;
  double[] arr2;
  boolean scalar;
  boolean[] results;
  int sz;
  

   // ---------------------------------------------------------------------
   //
   public TimeFilter(double begValue, double endValue) {
      this.begValue = begValue;
      this.endValue = endValue;
   }


   // ---------------------------------------------------------------------
   //
	public void newPointerCollection(PointerCollection pc, boolean[] results) {
		this.pc = pc;
		this.sz = pc.getSize();
		scalar = true;
		this.results = results;
		arr1 = pc.getTimeArr1();

		// If arr2 is null, times are a single scalar.
		arr2 = pc.getTimeArr2();
		
		if (arr2 != null) 
			scalar = false;
		
		if (scalar) {  
			// times are a scalar
			if (Debug.DEBUG_FILTER) 
				System.out.println("Time: Scalar");
		}
		else {  
			// times are each a range
			if (Debug.DEBUG_FILTER) 
				System.out.println("Time: Range of Time");
		}
	} 

   // ---------------------------------------------------------------------
   //
   // very brute force
   //
   public void startChanged(double oldValue, double newValue) {
      begValue = newValue;
      valueChange();
   }
   // ---------------------------------------------------------------------
   //
   public void stopChanged(double oldValue, double newValue) {
      endValue = newValue;
      valueChange();
   }
   // ---------------------------------------------------------------------
   //
   public void valueChange() {
      if (begValue > endValue) { // none
	for (int i = 0; i < sz; i++) results[i] = false;
	return;
      }
      if (scalar) {
	for (int i = 0; i < sz; i++) {
	   if ((arr1[i] >= begValue) && (arr1[i] <= endValue)) 
	     results[i] = true;
	   else 
	     results[i] = false;
	}
      }
      else {
	for (int i = 0; i < sz; i++) {
	   if (!(begValue > arr2[i] || endValue < arr1[i])) 
	     results[i] = true;
	   else 
	     results[i] = false;
	}
      }
   }
   
	public void reset() {
	}
}
